### ISSUE TITLE
Using Any desync method i get this error once in a while:

### ISSUE THREAD

**Issue by ghost** [thelupa1488/Champion#3]
Something like the game was modified and when I verify the files they find 2 files that are not ok and after that, it works for some time then it happens again. I don't know any better way to explain this. I hope you get what I'm trying to say here.

**Comment by thelupa1488** [comment]
try reinstal csgo or watching in code desync.cpp & clientmode.cpp

**Comment by thelupa1488** [comment]
https://github.com/thelupa1488/Champion/blob/master/source/hooks/ClientMode.cpp#L1007
https://github.com/thelupa1488/Champion/blob/master/source/features/Desync.cpp#L89

**Comment by ghost** [comment]
I reinstalled the game and I just encountered it again. https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837
Some files appeared in the cs:go directory.

[bug.zip](https://github.com/thelupa1488/Champion/files/4725504/bug.zip)

**Comment by thelupa1488** [comment]
it's crash log & signature
![image](https://user-images.githubusercontent.com/32226207/83689577-54bb6700-a600-11ea-9b92-6324ca2e1b97.png)
